In [1]:
import csv
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1500)
pd.set_option('display.width', 1000)

Reading in the original csv file on cancer mortality rates and related variables from the https://data.world/exercises/linear-regression-exercise-1 page.

In [3]:
cancer = pd.read_csv('cancer_reg.csv', encoding='latin-1')

In [4]:
cancer.shape

(3047, 34)

In [5]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3047 entries, 0 to 3046
Data columns (total 34 columns):
avgAnnCount                3047 non-null float64
avgDeathsPerYear           3047 non-null int64
TARGET_deathRate           3047 non-null float64
incidenceRate              3047 non-null float64
medIncome                  3047 non-null int64
popEst2015                 3047 non-null int64
povertyPercent             3047 non-null float64
studyPerCap                3047 non-null float64
binnedInc                  3047 non-null object
MedianAge                  3047 non-null float64
MedianAgeMale              3047 non-null float64
MedianAgeFemale            3047 non-null float64
Geography                  3047 non-null object
AvgHouseholdSize           3047 non-null float64
PercentMarried             3047 non-null float64
PctNoHS18_24               3047 non-null float64
PctHS18_24                 3047 non-null float64
PctSomeCol18_24            762 non-null float64
PctBachDeg18_24     

In [6]:
cancer.head()

avgAnnCount  avgDeathsPerYear  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap           binnedInc  MedianAge  MedianAgeMale  MedianAgeFemale                     Geography  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite  PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate
0       1397.0               469             164.9          489.8      61898      260131            11.2   499.748204   (61494.5, 125635]       39.3           36.9             41.7     Kitsap County, Washington              2.54            52.5          11.5        39.5             42.1              6.9          23.2               19.6                51.9                   8.0                75.1                      NaN                41.6               32.9                    14.0  81.780529  2.594728  4.821857      1.843479             52.856076   6.118831
1        173.0                70             161.3          411.6      48127       43269            18.6    23.111234  (48021.6, 51046.4]       33.0           32.2             33.7   Kittitas County, Washington              2.34            44.5           6.1        22.4             64.0              7.5          26.0               22.7                55.9                   7.8                70.2                     53.8                43.6               31.1                    15.3  89.228509  0.969102  2.246233      3.741352             45.372500   4.333096
2        102.0                50             174.7          349.7      49348       21026            14.6    47.560164  (48021.6, 51046.4]       45.0           44.0             45.8  Klickitat County, Washington              2.62            54.2          24.0        36.6              NaN              9.5          29.0               16.0                45.9                   7.0                63.7                     43.5                34.9               42.1                    21.1  90.922190  0.739673  0.465898      2.747358             54.444868   3.729488
3        427.0               202             194.8          430.4      44243       75882            17.1   342.637253    (42724.4, 45201]       42.8           42.2             43.4      Lewis County, Washington              2.52            52.7          20.2        41.2             36.1              2.5          31.6                9.3                48.3                  12.1                58.4                     40.3                35.0               45.3                    25.0  91.744686  0.782626  1.161359      1.362643             51.021514   4.603841
4         57.0                26             144.4          350.1      49955       10321            12.5     0.000000  (48021.6, 51046.4]       48.3           47.8             48.9    Lincoln County, Washington              2.34            57.8          14.9        43.0             40.0              2.0          33.4               15.0                48.2                   4.8                61.6                     43.9                35.1               44.0                    22.7  94.104024  0.270192  0.665830      0.492135             54.027460   6.796657

In [7]:
cancer.describe()

avgAnnCount  avgDeathsPerYear  TARGET_deathRate  incidenceRate      medIncome    popEst2015  povertyPercent  studyPerCap    MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24   PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone     PctWhite     PctBlack     PctAsian  PctOtherRace  PctMarriedHouseholds    BirthRate
count   3047.000000       3047.000000       3047.000000    3047.000000    3047.000000  3.047000e+03     3047.000000  3047.000000  3047.000000    3047.000000      3047.000000       3047.000000     3047.000000   3047.000000  3047.000000       762.000000      3047.000000   3047.000000        3047.000000         2895.000000           3047.000000         3047.000000              2438.000000         3047.000000        3047.000000             3047.000000  3047.000000  3047.000000  3047.000000   3047.000000           3047.000000  3047.000000
mean     606.338544        185.965868        178.664063     448.268586   47063.281917  1.026374e+05       16.878175   155.399415    45.272333      39.570725        42.145323          2.479662       51.773679     18.224450    35.002068        40.977034         6.158287     34.804660          13.282015           54.152642              7.852412           64.354939                48.453774           41.196324          36.252642               19.240072    83.645286     9.107978     1.253965      1.983523             51.243872     5.640306
std     1416.356223        504.134286         27.751511      54.560733   12040.090836  3.290592e+05        6.409087   529.628366    45.304480       5.226017         5.292849          0.429174        6.896928      8.093064     9.069722        11.115805         4.529059      7.034924           5.394756            8.315064              3.452371           10.647057                10.083006            9.447687           7.841741                6.113041    16.380025    14.534538     2.610276      3.517710              6.572814     1.985816
min        6.000000          3.000000         59.700000     201.300000   22640.000000  8.270000e+02        3.200000     0.000000    22.300000      22.400000        22.300000          0.022100       23.100000      0.000000     0.000000         7.100000         0.000000      7.500000           2.500000           17.600000              0.400000           22.300000                15.700000           13.500000          11.200000                2.600000    10.199155     0.000000     0.000000      0.000000             22.992490     0.000000
25%       76.000000         28.000000        161.200000     420.300000   38882.500000  1.168400e+04       12.150000     0.000000    37.700000      36.350000        39.100000          2.370000       47.750000     12.800000    29.200000        34.000000         3.100000     30.400000           9.400000           48.600000              5.500000           57.200000                41.000000           34.500000          30.900000               14.850000    77.296180     0.620675     0.254199      0.295172             47.763063     4.521419
50%      171.000000         61.000000        178.100000     453.549422   45207.000000  2.664300e+04       15.900000     0.000000    41.000000      39.600000        42.400000          2.500000       52.400000     17.100000    34.700000        40.400000         5.400000     35.300000          12.300000           54.500000              7.600000           65.100000                48.700000           41.100000          36.300000               18.800000    90.059774     2.247576     0.549812      0.826185             51.669941     5.381478
75%      518.000000        149.000000        195.200000     480.850000   52492.000000  6.867100e+04       20.400000    83.650776    44.000000      42.500000        45.300000          2.630000       56.400000     22.700000    40.

In [8]:
cancer.columns

Index(['avgAnnCount', 'avgDeathsPerYear', 'TARGET_deathRate', 'incidenceRate', 'medIncome', 'popEst2015', 'povertyPercent', 'studyPerCap', 'binnedInc', 'MedianAge', 'MedianAgeMale', 'MedianAgeFemale', 'Geography', 'AvgHouseholdSize', 'PercentMarried', 'PctNoHS18_24', 'PctHS18_24', 'PctSomeCol18_24', 'PctBachDeg18_24', 'PctHS25_Over', 'PctBachDeg25_Over', 'PctEmployed16_Over', 'PctUnemployed16_Over', 'PctPrivateCoverage', 'PctPrivateCoverageAlone', 'PctEmpPrivCoverage', 'PctPublicCoverage', 'PctPublicCoverageAlone', 'PctWhite', 'PctBlack', 'PctAsian', 'PctOtherRace', 'PctMarriedHouseholds', 'BirthRate'], dtype='object')

Checking for duplicate rows in the DataFrame

In [9]:
cancer = cancer.drop_duplicates()
cancer.shape

(3047, 34)

## Missing Values

Checking for variables with missing values, using both the .isnull().sum() and .isna().sum() chained methods.

In [10]:
cancer.isnull().sum()

avgAnnCount                   0
avgDeathsPerYear              0
TARGET_deathRate              0
incidenceRate                 0
medIncome                     0
popEst2015                    0
povertyPercent                0
studyPerCap                   0
binnedInc                     0
MedianAge                     0
MedianAgeMale                 0
MedianAgeFemale               0
Geography                     0
AvgHouseholdSize              0
PercentMarried                0
PctNoHS18_24                  0
PctHS18_24                    0
PctSomeCol18_24            2285
PctBachDeg18_24               0
PctHS25_Over                  0
PctBachDeg25_Over             0
PctEmployed16_Over          152
PctUnemployed16_Over          0
PctPrivateCoverage            0
PctPrivateCoverageAlone     609
PctEmpPrivCoverage            0
PctPublicCoverage             0
PctPublicCoverageAlone        0
PctWhite                      0
PctBlack                      0
PctAsian                      0
PctOther

In [11]:
cancer.isna().sum()

avgAnnCount                   0
avgDeathsPerYear              0
TARGET_deathRate              0
incidenceRate                 0
medIncome                     0
popEst2015                    0
povertyPercent                0
studyPerCap                   0
binnedInc                     0
MedianAge                     0
MedianAgeMale                 0
MedianAgeFemale               0
Geography                     0
AvgHouseholdSize              0
PercentMarried                0
PctNoHS18_24                  0
PctHS18_24                    0
PctSomeCol18_24            2285
PctBachDeg18_24               0
PctHS25_Over                  0
PctBachDeg25_Over             0
PctEmployed16_Over          152
PctUnemployed16_Over          0
PctPrivateCoverage            0
PctPrivateCoverageAlone     609
PctEmpPrivCoverage            0
PctPublicCoverage             0
PctPublicCoverageAlone        0
PctWhite                      0
PctBlack                      0
PctAsian                      0
PctOther

A list of all the columns with missing values is called.

In [12]:
null_value_columns = list(cancer.columns[(cancer.isnull().sum()>0) | (cancer.isna().sum()>0)])
null_value_columns

['PctSomeCol18_24', 'PctEmployed16_Over', 'PctPrivateCoverageAlone']

For the columns with missing values, new '_isnull' columns are created to keep track of the fact that columns with missing values had these values filled with the median of their respective column.

In [13]:
for col_name in null_value_columns:
    new_col_name = col_name+'_isnull'
    print(col_name)
    cancer[new_col_name] = cancer[col_name].isnull()

PctSomeCol18_24
PctEmployed16_Over
PctPrivateCoverageAlone


In [14]:
cancer.head()

avgAnnCount  avgDeathsPerYear  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap           binnedInc  MedianAge  MedianAgeMale  MedianAgeFemale                     Geography  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite  PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull
0       1397.0               469             164.9          489.8      61898      260131            11.2   499.748204   (61494.5, 125635]       39.3           36.9             41.7     Kitsap County, Washington              2.54            52.5          11.5        39.5             42.1              6.9          23.2               19.6                51.9                   8.0                75.1                      NaN                41.6               32.9                    14.0  81.780529  2.594728  4.821857      1.843479             52.856076   6.118831                   False                      False                            True
1        173.0                70             161.3          411.6      48127       43269            18.6    23.111234  (48021.6, 51046.4]       33.0           32.2             33.7   Kittitas County, Washington              2.34            44.5           6.1        22.4             64.0              7.5          26.0               22.7                55.9                   7.8                70.2                     53.8                43.6               31.1                    15.3  89.228509  0.969102  2.246233      3.741352             45.372500   4.333096                   False                      False                           False
2        102.0                50             174.7          349.7      49348       21026            14.6    47.560164  (48021.6, 51046.4]       45.0           44.0             45.8  Klickitat County, Washington              2.62            54.2          24.0        36.6              NaN              9.5          29.0               16.0                45.9                   7.0                63.7                     43.5                34.9               42.1                    21.1  90.922190  0.739673  0.465898      2.747358             54.444868   3.729488                    True                      False                           False
3        427.0               202             194.8          430.4      44243       75882            17.1   342.637253    (42724.4, 45201]       42.8           42.2             43.4      Lewis County, Washington              2.52            52.7          20.2        41.2             36.1              2.5          31.6                9.3                48.3                  12.1                58.4                     40.3                35.0               45.3                    25.0  91.744686  0.782626  1.161359      1.362643             51.021514   4.603841                   False                      False                           False
4         57.0                26             144.4          350.1      49955       10321            12.5     0.000000  (48021.6, 51046.4]       48.3           47.8             48.9    Lincoln County, Washington              2.34            57.8          14.9        43.0             40.0              2.0          33.4               15.0                48.2                   4.8                61.6                     43.9                35.1               44.0                    22.7  94.104024  0.270192  0.665830      0.492135             54.027460   6.796657                   False                      False                           False

The median is called for each of these columns with missing values for filling purposes.

In [15]:
SomeCol18_24_median = cancer['PctSomeCol18_24'].median()
SomeCol18_24_median

40.4

In [16]:
PctEmployed16_Over_median = cancer['PctEmployed16_Over'].median()
PctEmployed16_Over_median

54.5

In [17]:
PctPrivateCoverageAlone_median = cancer['PctPrivateCoverageAlone'].median()
PctPrivateCoverageAlone_median

48.7

The missing values are filled with that column's median value.

In [18]:
cancer['PctSomeCol18_24'] = cancer['PctSomeCol18_24'].fillna(value = SomeCol18_24_median)

In [19]:
cancer['PctEmployed16_Over'] = cancer['PctEmployed16_Over'].fillna(value = PctEmployed16_Over_median)

In [20]:
cancer['PctPrivateCoverageAlone'] = cancer['PctPrivateCoverageAlone'].fillna(value = PctPrivateCoverageAlone_median)

The presence of columns with missing values is again called to verify that all missing values have been filled.

In [21]:
null_value_columns = list(cancer.columns[(cancer.isnull().sum()>0) | (cancer.isna().sum()>0)])
null_value_columns

[]

## Erroneous Values

As is seen below, there are 30 counties where the age is over 100. In the '2nd_Capstone_Cancer_LogExp_Expansion' notebook, it was noticed that there are 30 cases where the age is well over 100, into the 200-600 year old range. So it is obvious that these values are erroneous, and are replaced by the median value of the 'MedianAge' column in the next series of cells.

In [22]:
cancer['age_gt_100'] = cancer['MedianAge'] > 100

In [23]:
cancer['age_gt_100'].value_counts()

False    3017
True       30
Name: age_gt_100, dtype: int64

In [24]:
MedianAge_median = cancer['MedianAge'].median()
MedianAge_median

41.0

In [25]:
true_median_age = {True: MedianAge_median}

In [26]:
cancer.loc[cancer['MedianAge'] > 100,'MedianAge']=np.nan

In [27]:
cancer.MedianAge = cancer.MedianAge.fillna(cancer.age_gt_100.map(true_median_age))

In [28]:
cancer.MedianAge.value_counts()

41.0    72
42.2    36
38.8    35
40.7    34
40.1    34
42.6    32
42.8    32
41.5    31
40.6    30
40.9    30
41.3    29
39.8    29
40.8    29
39.7    29
39.9    28
43.0    28
41.8    28
42.3    27
40.5    27
41.7    27
42.1    26
39.3    26
40.3    26
39.0    26
41.1    26
41.6    25
42.9    25
38.5    25
41.9    24
41.4    24
38.4    24
43.2    24
43.6    24
43.5    24
42.4    23
38.9    23
40.4    23
39.1    23
41.2    23
42.0    23
43.7    23
38.0    22
39.2    22
44.1    22
39.5    22
43.1    22
44.2    21
43.3    21
43.4    20
40.0    20
39.6    20
37.6    20
36.1    20
42.5    20
37.0    19
39.4    19
37.8    19
35.5    19
34.8    19
43.9    19
43.8    19
37.7    19
38.6    18
37.5    18
37.4    18
40.2    18
37.9    17
38.1    17
36.8    17
45.4    17
44.9    17
36.9    17
44.3    17
37.1    16
36.7    16
36.0    16
44.5    16
38.2    16
36.5    16
36.6    16
45.1    16
45.0    15
44.8    15
46.1    15
35.8    15
47.1    15
34.6    15
37.3    14
44.4    14
44.7    14
42.7    14

It was also noticed in the '2nd_Capstone_Cancer_LogExp_Expansion' notebook that there are 61 counties where the average household size for occupied housing units (variable name 'AvgHouseholdSize') is less than one, ranging from 0.0221 to 0.0322. This is again erroneous, as the Census data that this is taken from explicitly states that the 'AvgHouseholdSize' variable stores the average household size for OCCUPIED housing units. Therefore, these counties will have their value filled by the median value in the next series of cells.

In [29]:
cancer['household_lt_1'] = cancer['AvgHouseholdSize'] < 1

In [30]:
cancer['household_lt_1'].value_counts()

False    2986
True       61
Name: household_lt_1, dtype: int64

In [31]:
AvgHouseholdSize_median = cancer['AvgHouseholdSize'].median()
AvgHouseholdSize_median

2.5

In [32]:
true_avghouseholdsize = {True: AvgHouseholdSize_median}

In [33]:
cancer.loc[cancer['AvgHouseholdSize'] < 1,'AvgHouseholdSize']=np.nan

In [34]:
cancer.AvgHouseholdSize = cancer.AvgHouseholdSize.fillna(cancer.household_lt_1.map(true_avghouseholdsize))

In [35]:
cancer.AvgHouseholdSize.value_counts()

2.50    117
2.52     75
2.48     70
2.55     68
2.44     67
2.43     66
2.45     65
2.49     64
2.38     62
2.51     60
2.57     60
2.37     59
2.53     59
2.39     55
2.35     54
2.46     54
2.40     53
2.54     53
2.56     53
2.58     52
2.36     52
2.62     51
2.47     51
2.42     50
2.61     50
2.59     47
2.41     46
2.63     46
2.60     44
2.34     42
2.65     41
2.33     40
2.70     35
2.25     33
2.31     33
2.67     33
2.32     32
2.28     32
2.68     32
2.30     32
2.66     29
2.29     29
2.26     29
2.27     28
2.24     28
2.72     27
2.64     26
2.71     26
2.75     25
2.78     25
2.69     24
2.21     24
2.76     23
2.22     21
2.74     21
2.73     20
2.81     19
2.77     19
2.86     18
2.20     17
2.18     16
2.83     15
2.84     14
2.15     14
2.85     14
2.19     13
2.23     13
2.80     13
2.87     13
2.79     12
2.08     11
2.14     11
2.98     11
2.82     11
2.13     10
3.08     10
2.10     10
2.16     10
3.04      9
3.00      8
2.12      8
2.17      8
2.90      8
2.96

## Data Leakage

In order to avoid data leakage in the machine learning models, the feature called 'avgdeathsperyear' is dropped below, as it contains the mean number of reported fatalities due to cancer, while the target variable 'target_deathrate' contains the mean per capita (100,000) cancer mortalities. Essentially, 'avgdeathsperyear' stores the same information as the target variable, just non-normalized.

In [36]:
cancer = cancer.drop('avgDeathsPerYear', axis=1)

In [37]:
cancer.shape

(3047, 38)

## Binarization of Categorical Variable 'binnedInc'

The one native feature from the original DataFrame that will need to be binarized for machine learning purposes is 'binnedInc', the median income per capita binned by decile. The data type of this variable is first confirmed as being 'string'.

In [38]:
type(cancer['binnedInc'].iloc[0])

str

In [39]:
cancer_ml = pd.get_dummies(cancer, columns=['binnedInc'])

The binarization of the 'binnedInc' feature is confirmed in the new DataFrame 'cancer_ml'.

In [40]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale                     Geography  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite  PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]
0       1397.0             164.9          489.8      61898      260131            11.2   499.748204       39.3           36.9             41.7     Kitsap County, Washington              2.54            52.5          11.5        39.5             42.1              6.9          23.2               19.6                51.9                   8.0                75.1                     48.7                41.6               32.9                    14.0  81.780529  2.594728  4.821857      1.843479             52.856076   6.118831                   False                      False                            True       False           False                             0                             0                             0                           0                           0                             0                             0                             0                            1                           0
1        173.0             161.3          411.6      48127       43269            18.6    23.111234       33.0           32.2             33.7   Kittitas County, Washington              2.34            44.5           6.1        22.4             64.0              7.5          26.0               22.7                55.9                   7.8                70.2                     53.8                43.6               31.1                    15.3  89.228509  0.969102  2.246233      3.741352             45.372500   4.333096                   False                      False                           False       False           False                             0                             0                             0                           0                           0                             1                             0                             0                            0                           0
2        102.0             174.7          349.7      49348       21026            14.6    47.560164       45.0           44.0             45.8  Klickitat County, Washington              2.62            54.2          24.0        36.6             40.4              9.5          29.0               16.0                45.9                   7.0                63.7                     43.5                34.9               42.1                    21.1  90.922190  0.739673  0.465898      2.747358             54.444868   3.729488                    True                      False                           False       False           False                             0                             0                             0                           0                           0                             1                             0                             0                            0                           0
3        427.0             194.8          430.4      44243       75882            17.1   342.637253       42.8           42.2             43.4      Lewis County, Washington              2.52            52.7          20.2        41.2             36.1              2.5         

In [41]:
cancer_ml.shape

(3047, 47)

The 'cancer_ml' DataFrame is exported to csv so that it can be re-imported with the proper index 'Geography', which stores the county and state data. Each row of the DataFrame will store one county's data.

In [42]:
cancer_ml.to_csv('cancer_ml.csv')

The original 'cancer' DataFrame is deleted as it is no longer needed.

In [43]:
del cancer

# Merging in county latitude/longitude centroids

County centroids are found at https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2019_Gazetteer/2019_Gaz_counties_national.zip

In [44]:
cnty_centroids = pd.read_csv('2019_Gaz_counties_national.csv', index_col=['Geography'], encoding='latin-1')

In [45]:
cnty_centroids.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3142 entries, Autauga County, Alabama to Weston County, Wyoming
Data columns (total 10 columns):
State          3142 non-null object
GEOID          3142 non-null int64
ANSICODE       3142 non-null int64
NAME           3142 non-null object
ALAND          3142 non-null float64
AWATER         3142 non-null int64
ALAND_SQMI     3142 non-null float64
AWATER_SQMI    3142 non-null float64
INTPTLAT       3142 non-null float64
INTPTLONG      3142 non-null float64
dtypes: float64(5), int64(3), object(2)
memory usage: 270.0+ KB


In [46]:
cnty_centroids.head()

State  GEOID  ANSICODE            NAME         ALAND      AWATER  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG
Geography                                                                                                                                 
Autauga County, Alabama  Alabama   1001    161526  Autauga County  1.539602e+09    25706961     594.444        9.926  32.532237 -86.646440
Baldwin County, Alabama  Alabama   1003    161527  Baldwin County  4.117622e+09  1132980868    1589.823      437.446  30.659218 -87.746067
Barbour County, Alabama  Alabama   1005    161528  Barbour County  2.292160e+09    50523213     885.008       19.507  31.870253 -85.405104
Bibb County, Alabama     Alabama   1007    161529     Bibb County  1.612167e+09     9602089     622.461        3.707  33.015893 -87.127148
Blount County, Alabama   Alabama   1009    161530   Blount County  1.670104e+09    15015467     644.831        5.798  33.977358 -86.566440

Delete and re-import 'cancer_ml' DataFrame to set index to the 'Geography' variable.

In [47]:
del cancer_ml

In [48]:
cancer_ml = pd.read_csv('cancer_ml.csv', index_col=['Geography'])

In [49]:
cancer_ml.head()

Unnamed: 0  avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite  PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
Kitsap County, Washington              0       1397.0             164.9          489.8      61898      260131            11.2   499.748204       39.3           36.9             41.7              2.54            52.5          11.5        39.5             42.1              6.9          23.2               19.6                51.9                   8.0                75.1                     48.7                41.6               32.9                    14.0  81.780529  2.594728  4.821857      1.843479             52.856076   6.118831                   False                      False                            True       False           False                             0                             0                             0                           0                           0                             0                             0                             0                            1                           0
Kittitas County, Washington            1        173.0             161.3          411.6      48127       43269            18.6    23.111234       33.0           32.2             33.7              2.34            44.5           6.1        22.4             64.0              7.5          26.0               22.7                55.9                   7.8                70.2                     53.8                43.6               31.1                    15.3  89.228509  0.969102  2.246233      3.741352             45.372500   4.333096                   False                      False                           False       False           False                             0                             0                             0                           0                           0                             1                             0                             0                            0                           0
Klickitat County, Washington           2        102.0             174.7          349.7      49348       21026            14.6    47.560164       45.0           44.0             45.8              2.62            54.2          24.0        36.6             40.4        

The column with the original default row number index is dropped as it is no longer needed.

In [50]:
cancer_ml = cancer_ml.drop('Unnamed: 0', axis=1)

The presence of duplicates is checked for in the county centroids file.

In [51]:
cnty_centroids.shape

(3142, 10)

In [52]:
cnty_centroids.drop_duplicates()
cnty_centroids.shape

(3142, 10)

The machine learning friendly DataFrame and the county centroids DataFrame are concatenated.

In [53]:
cancer_ml = pd.concat([cancer_ml, cnty_centroids], axis=1, sort=True)
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate PctSomeCol18_24_isnull PctEmployed16_Over_isnull PctPrivateCoverageAlone_isnull age_gt_100 household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]           State    GEOID   ANSICODE              NAME         ALAND  \
Abbeville County, South Carolina        143.0             183.7          430.9    35525.0     24932.0            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                   True                     False                          False      False          False                           1.0                           0.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0  South Carolina  45001.0  1245666.0  Abbeville County  1.272790e+09   
Acadia Parish, Louisiana                323.0             230.5          492.7    40269.0     62577.0            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                  False                     False                          False      False          False                           0.0                           1.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0       Louisiana  22001.0   558389.0     Acadia Parish  1.696881e+09   
Accomack County, Virginia               221.0             216.2          479.4    38390.0     32973.0            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                   True                     False                          False      False          False                           0.0                           1.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0        Virginia  51001.0  1480091.0   Accomack County  1.163708e+09   
Ada County, Idaho                 

In [54]:
cancer_ml.shape

(3180, 56)

In [55]:
cancer_ml.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3180 entries, Abbeville County, South Carolina to Ziebach County, South Dakota
Data columns (total 56 columns):
avgAnnCount                       3047 non-null float64
TARGET_deathRate                  3047 non-null float64
incidenceRate                     3047 non-null float64
medIncome                         3047 non-null float64
popEst2015                        3047 non-null float64
povertyPercent                    3047 non-null float64
studyPerCap                       3047 non-null float64
MedianAge                         3047 non-null float64
MedianAgeMale                     3047 non-null float64
MedianAgeFemale                   3047 non-null float64
AvgHouseholdSize                  3047 non-null float64
PercentMarried                    3047 non-null float64
PctNoHS18_24                      3047 non-null float64
PctHS18_24                        3047 non-null float64
PctSomeCol18_24                   3047 non-null float64
Pct

Looking at missing value in the concatenated DataFrame of the Cancer DataFrame and County Centroids DataFrame, there are 133 counties or territories in the county centroids DataFrame that are not in the cancer DataFrame. We are only interested in the counties that have the cancer-related data, so these 133 counties will be dropped. 

There are also 38 counties in the Cancer DataFrame that are not in the County Centroids DataFrame. These counties will be kept, but their centroids and land/water area will be looked up manually through Google search.

In [56]:
cancer_ml.isnull().sum()

avgAnnCount                       133
TARGET_deathRate                  133
incidenceRate                     133
medIncome                         133
popEst2015                        133
povertyPercent                    133
studyPerCap                       133
MedianAge                         133
MedianAgeMale                     133
MedianAgeFemale                   133
AvgHouseholdSize                  133
PercentMarried                    133
PctNoHS18_24                      133
PctHS18_24                        133
PctSomeCol18_24                   133
PctBachDeg18_24                   133
PctHS25_Over                      133
PctBachDeg25_Over                 133
PctEmployed16_Over                133
PctUnemployed16_Over              133
PctPrivateCoverage                133
PctPrivateCoverageAlone           133
PctEmpPrivCoverage                133
PctPublicCoverage                 133
PctPublicCoverageAlone            133
PctWhite                          133
PctBlack    

The presence of missing values is again called. There are 133 counties in the Census county centroids dataset that are not in the original cancer dataset. There are also 38 counties in the original cancer dataset that are not in the Census county centroids dataset.

In [57]:
cancer_ml.isna().sum()

avgAnnCount                       133
TARGET_deathRate                  133
incidenceRate                     133
medIncome                         133
popEst2015                        133
povertyPercent                    133
studyPerCap                       133
MedianAge                         133
MedianAgeMale                     133
MedianAgeFemale                   133
AvgHouseholdSize                  133
PercentMarried                    133
PctNoHS18_24                      133
PctHS18_24                        133
PctSomeCol18_24                   133
PctBachDeg18_24                   133
PctHS25_Over                      133
PctBachDeg25_Over                 133
PctEmployed16_Over                133
PctUnemployed16_Over              133
PctPrivateCoverage                133
PctPrivateCoverageAlone           133
PctEmpPrivCoverage                133
PctPublicCoverage                 133
PctPublicCoverageAlone            133
PctWhite                          133
PctBlack    

In [58]:
cancer_ml.shape

(3180, 56)

133 rows from the Census county centroids dataset that do not exist in the original cancer dataset are dropped because no cancer-related data exists for them. This is done by identifying the counties with no value for the target variable 'TARGET_deathRate', and dropping them.

In [59]:
cancer_ml = cancer_ml.drop(cancer_ml[cancer_ml.TARGET_deathRate.isnull()].index)

There are now 3,047 rows, which matches the 3,047 counties in the original cancer dataset.

In [60]:
cancer_ml.shape

(3047, 56)

In [61]:
cancer_ml.columns

Index(['avgAnnCount', 'TARGET_deathRate', 'incidenceRate', 'medIncome', 'popEst2015', 'povertyPercent', 'studyPerCap', 'MedianAge', 'MedianAgeMale', 'MedianAgeFemale', 'AvgHouseholdSize', 'PercentMarried', 'PctNoHS18_24', 'PctHS18_24', 'PctSomeCol18_24', 'PctBachDeg18_24', 'PctHS25_Over', 'PctBachDeg25_Over', 'PctEmployed16_Over', 'PctUnemployed16_Over', 'PctPrivateCoverage', 'PctPrivateCoverageAlone', 'PctEmpPrivCoverage', 'PctPublicCoverage', 'PctPublicCoverageAlone', 'PctWhite', 'PctBlack', 'PctAsian', 'PctOtherRace', 'PctMarriedHouseholds', 'BirthRate', 'PctSomeCol18_24_isnull', 'PctEmployed16_Over_isnull', 'PctPrivateCoverageAlone_isnull', 'age_gt_100', 'household_lt_1', 'binnedInc_(34218.1, 37413.8]', 'binnedInc_(37413.8, 40362.7]', 'binnedInc_(40362.7, 42724.4]', 'binnedInc_(42724.4, 45201]', 'binnedInc_(45201, 48021.6]', 'binnedInc_(48021.6, 51046.4]', 'binnedInc_(51046.4, 54545.6]', 'binnedInc_(54545.6, 61494.5]', 'binnedInc_(61494.5, 125635]', 'binnedInc_[22640, 34218.1]',
  

The following columns that came from the Census county centroids dataset are dropped: 

'GEOID' and 'ANSICODE' are unique identifers that will lead to overfitting in the machine learning models and don't have any relevant information. 

'NAME' is the county name, and that information is stored in the index. 

The 'ALAND' and 'AWATER' variables are acreage, which is duplicative of the square mileage data stored in 'ALAND_SQMI' and 'AWATER_SQMI'.

In [62]:
cancer_ml = cancer_ml.drop(columns=['GEOID', 'ANSICODE', 'NAME', 'ALAND', 'AWATER'])

In [63]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate PctSomeCol18_24_isnull PctEmployed16_Over_isnull PctPrivateCoverageAlone_isnull age_gt_100 household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]           State  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG
Abbeville County, South Carolina        143.0             183.7          430.9    35525.0     24932.0            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                   True                     False                          False      False          False                           1.0                           0.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0  South Carolina     491.427       20.554  34.229041  -82.454058
Acadia Parish, Louisiana                323.0             230.5          492.7    40269.0     62577.0            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                  False                     False                          False      False          False                           0.0                           1.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0       Louisiana     655.169        2.285  30.291497  -92.411037
Accomack County, Virginia               221.0             216.2          479.4    38390.0     32973.0            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                   True                     False                          False      False          False                           0.0                           1.0                           0.0                         0.0                         0.0                           0.0                           0.0                           0.0                          0.0                         0.0        Virginia     449.310      860.729  37.765944  -75.757807
Ada County, Idaho                      1757.0             151.

In [64]:
cancer_ml.shape

(3047, 51)

The land/water area and county centroids still need to be entered for the 38 counties in the original Cancer DataFrame that did not exist in the County Centroids DataFrame. This is shown in the .isnull().sum() call below.

In [65]:
cancer_ml.isnull().sum()

avgAnnCount                        0
TARGET_deathRate                   0
incidenceRate                      0
medIncome                          0
popEst2015                         0
povertyPercent                     0
studyPerCap                        0
MedianAge                          0
MedianAgeMale                      0
MedianAgeFemale                    0
AvgHouseholdSize                   0
PercentMarried                     0
PctNoHS18_24                       0
PctHS18_24                         0
PctSomeCol18_24                    0
PctBachDeg18_24                    0
PctHS25_Over                       0
PctBachDeg25_Over                  0
PctEmployed16_Over                 0
PctUnemployed16_Over               0
PctPrivateCoverage                 0
PctPrivateCoverageAlone            0
PctEmpPrivCoverage                 0
PctPublicCoverage                  0
PctPublicCoverageAlone             0
PctWhite                           0
PctBlack                           0
P

The merged current DataFrame is exported to csv for manual updating of state, land/water area and county centroids for the 38 counties that did not have this information in the Census county centroids dataset. The land/water area and county centroids for these 38 counties were found from Google search.

In [67]:
cancer_ml.to_csv('cancer_ml_centroids.csv')

In [68]:
del cancer_ml

In [3]:
cancer_ml = pd.read_csv('cancer_ml_centroids.csv', index_col=['Geography'])

After manual editing, the presence of missing values is checked for again.

In [4]:
null_value_cols = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_cols

[]

The 'State' feature must be binarized for machine learning purposes, as it is currently a string feature.

In [6]:
cancer_ml = pd.get_dummies(cancer_ml, columns=['State'])

In [7]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia         

# Distances to Top 10 Oncology Hospitals and Regional Cities as Predictive Features

The following section computes the L1 and L2 distances of each county from the nation's top 10 oncology hospitals, and from the main large regional cities of the U.S. The top 10 oncology hospitals were from the 2019 ratings found at https://health.usnews.com/best-hospitals/rankings/cancer . The latitudes and longitudes of the top 10 oncology hospitals and of the large regional cities of the U.S. were found from Google search.

In [8]:
lat_long = pd.DataFrame(dict(utmda = dict(lat= 29.7078, lon= 95.3974), mskcc = dict(lat= 40.7646, lon= 73.9635), 
                        mayo = dict(lat= 44.0227, lon= 92.4673), hopkins = dict(lat= 39.2967, lon= 76.5927), 
                        dfb = dict(lat= 42.3375, lon= 71.1082), cleveland = dict(lat= 41.5032, lon= 81.6212),  
                        upmcps = dict(lat= 40.4421, lon= 79.9608), hlmcc = dict(lat= 28.0655, lon= 82.4212), 
                        mgs = dict(lat= 42.3626, lon= 71.0676), nw_mem = dict(lat= 41.895, lon= 87.6215), 
                        chi = dict(lat= 41.8781, lon= 87.6298), nyc = dict(lat= 40.7128, lon= 74.006), 
                        atlanta = dict(lat= 33.749, lon= 84.388), dallas = dict(lat= 32.7767, lon= 96.797), 
                        denver = dict(lat= 39.7392, lon= 104.9903), los_ang = dict(lat= 34.0522, lon= 118.2437), 
                        seattle = dict(lat= 47.6062, lon= 122.3321), san_fran = dict(lat= 37.7749, lon= 122.4194)))
lat_long = lat_long.T
lat_long['lon'] = - lat_long['lon']
lat_long

lat       lon
utmda      29.7078  -95.3974
mskcc      40.7646  -73.9635
mayo       44.0227  -92.4673
hopkins    39.2967  -76.5927
dfb        42.3375  -71.1082
cleveland  41.5032  -81.6212
upmcps     40.4421  -79.9608
hlmcc      28.0655  -82.4212
mgs        42.3626  -71.0676
nw_mem     41.8950  -87.6215
chi        41.8781  -87.6298
nyc        40.7128  -74.0060
atlanta    33.7490  -84.3880
dallas     32.7767  -96.7970
denver     39.7392 -104.9903
los_ang    34.0522 -118.2437
seattle    47.6062 -122.3321
san_fran   37.7749 -122.4194

In [9]:
for name in lat_long.index:
    cancer_ml[name+'_l1'] = abs(cancer_ml.INTPTLAT - lat_long['lat'][name]) + abs(cancer_ml.INTPTLONG - lat_long['lon'][name])

The first row's values of the 'cancer_ml' DataFrame are called to verify that all of the new continuous geographic L1 features were created.

In [10]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

In [11]:
for name in lat_long.index:
    cancer_ml[name+'_l2'] = ((cancer_ml.INTPTLAT - lat_long['lat'][name])**2 + (cancer_ml.INTPTLONG - lat_long['lon'][name])**2)**0.5

The first row's values of the 'cancer_ml' DataFrame are called to verify that all of the new continuous geographic L2 features were created.

In [12]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

The next series of cells calculates the L1 distance of each county to the closest top 10 oncology hospital.

In [13]:
oncology_features_l1 = ['utmda_l1', 'mskcc_l1', 'mayo_l1', 'hopkins_l1', 'dfb_l1', 'cleveland_l1', 'upmcps_l1', 
                    'hlmcc_l1', 'mgs_l1', 'nw_mem_l1']

In [14]:
onc_min_distsl1 = cancer_ml[oncology_features_l1].min(axis=1).values
onc_min_distsl1

array([ 6.196399,  3.57006 ,  2.365649, ..., 13.976279,  6.496022,
        5.205578])

A new feature is created in the 'cancer_ml' DataFrame which stores the L1 latitude/longitude distance of each county to the closest top 10 oncology hospital.

In [15]:
cancer_ml['onc_min_distsl1'] = onc_min_distsl1

The first row's values of the 'cancer_ml_c' DataFrame are called to verify that the new closest L1 top 10 oncology hospital feature was created.

In [16]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

The next series of cells calculates the L2 distance of each county to the closest top 10 oncology hospital.

In [17]:
oncology_features_l2 = ['utmda_l2', 'mskcc_l2', 'mayo_l2', 'hopkins_l2', 'dfb_l2', 'cleveland_l2', 'upmcps_l2', 
                    'hlmcc_l2', 'mgs_l2', 'nw_mem_l2']

In [18]:
onc_min_distsl2 = cancer_ml[oncology_features_l2].min(axis=1).values
onc_min_distsl2

array([ 6.16362858,  3.04287137,  1.74363421, ..., 10.73615317,
        4.6557815 ,  4.44316262])

A new feature is created in the 'cancer_ml' DataFrame which stores the L2 latitude/longitude distance of each county to the closest top 10 oncology hospital.

In [19]:
cancer_ml['onc_min_distsl2'] = onc_min_distsl2

The first row's values of the 'cancer_ml' DataFrame are called to verify that the new closest L2 top 10 oncology hospital feature was created.

In [20]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

## Closest Regional City

The next series of cells calculates the L1 distance of each county to the closest regional city center.

In [21]:
city_features_l1 = ['chi_l1', 'nyc_l1', 'atlanta_l1', 'dallas_l1', 'denver_l1', 'los_ang_l1', 'seattle_l1', 'san_fran_l1']

In [22]:
city_min_distsl1 = cancer_ml[city_features_l1].min(axis=1).values
city_min_distsl1

array([2.413983, 6.871166, 4.698663, ..., 2.830221, 8.165322, 6.874878])

A new feature is created in the 'cancer_ml' DataFrame which stores the L1 latitude/longitude distance of each county to the closest major regional city.

In [23]:
cancer_ml['city_min_distsl1'] = city_min_distsl1

The first row's values of the 'cancer_ml' DataFrame are called to verify that the new closest L1 major regional city feature was created.

In [24]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

The next series of cells calculates the L2 distance of each county to the closest regional city center.

In [25]:
city_features_l2 = ['chi_l2', 'nyc_l2', 'atlanta_l2', 'dallas_l2', 'denver_l2', 'los_ang_l2', 'seattle_l2', 'san_fran_l2']

In [26]:
city_min_distsl2 = cancer_ml[city_features_l2].min(axis=1).values
city_min_distsl2

array([1.99262917, 5.04112144, 3.42823395, ..., 2.58193471, 6.25269969,
       4.90739046])

A new feature is created in the 'cancer_ml' DataFrame which stores the L2 latitude/longitude distance of each county to the closest major regional city.

In [27]:
cancer_ml['city_min_distsl2'] = city_min_distsl2

The first row's values of the 'cancer_ml' DataFrame are called to verify that the new closest L2 major regional city feature was created.

In [28]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

## Benchmark 1

This is a good place to output a csv file as a benchmark before more features are added.

In [29]:
cancer_ml.to_csv('cancer_ml_benchmark_1.csv')

In [30]:
cancer_ml = pd.read_csv('cancer_ml_benchmark_1.csv', index_col=['Geography'])

In [31]:
cancer_ml.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Abbeville County, South Carolina to Zavala County, Texas
Columns: 141 entries, avgAnnCount to city_min_distsl2
dtypes: bool(5), float64(73), int64(63)
memory usage: 3.2+ MB


In [32]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

# Distance to Superfund Cleanup Sites

Because the local environment can influence cancer mortality, the distance of each county to Superfund Cleanup Sites (as designated by the Environmental Protection Agency) and the distance to the closest Superfund Cleanup site is added to the feature set in the following series of cells. The latitude and longitude location of each Superfund Cleanup site was downloaded from the EPA's website at https://semspub.epa.gov/work/HQ/201261.pdf. The file had an embedded Excel spreadsheet that was converted into csv; only the name of the site, the latitude, and the longitude were kept.

In [33]:
sc_sites = pd.read_csv('superfund_sites_50states_cleaned.csv', index_col=['Site_Name'])

In [34]:
sc_sites.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1313 entries, SC_EASTERN SURPLUS to SC_WRIGHT GROUND WATER CONTAMINATION
Data columns (total 2 columns):
lat    1313 non-null float64
lon    1313 non-null float64
dtypes: float64(2)
memory usage: 30.8+ KB


In [35]:
sc_sites.head(1)

lat        lon
Site_Name                               
SC_EASTERN SURPLUS  45.038889 -67.358333

In [36]:
for name in sc_sites.index:
    cancer_ml[name+'_l1'] = abs(cancer_ml.INTPTLAT - sc_sites['lat'][name]) + abs(cancer_ml.INTPTLONG - sc_sites['lon'][name])

The first row's values of the 'cancer_ml' DataFrame are called to verify that all of the new continuous geographic L1 features were created.

In [37]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

In [38]:
cancer_ml.shape

(3047, 1454)

In [39]:
for name in sc_sites.index:
    cancer_ml[name+'_l2'] = ((cancer_ml.INTPTLAT - sc_sites['lat'][name])**2 + (cancer_ml.INTPTLONG - sc_sites['lon'][name])**2)**0.5

The first row's values of the 'cancer_ml' DataFrame are called to verify that all of the new continuous geographic L2 features were created.

In [40]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

In [41]:
cancer_ml.shape

(3047, 2767)

The next series of cells calculates the L1 distance of each county to the closest Superfund Cleanup site.

In [42]:
sc_site_features_l1 = list(cancer_ml.columns[cancer_ml.columns.str.startswith('SC') & cancer_ml.columns.str.endswith('_l1')])

In [43]:
sc_min_dists_l1 = cancer_ml[sc_site_features_l1].min(axis=1).values
sc_min_dists_l1

array([0.509339, 0.249904, 1.166387, ..., 1.808657, 1.980829, 1.593792])

A new feature is created in the 'cancer_ml' DataFrame which stores the L1 latitude/longitude distance of each county to the closest Superfund Cleanup site.

In [44]:
cancer_ml['sc_min_dists_l1'] = sc_min_dists_l1

The first row's values of the 'cancer_ml' DataFrame are called to verify that the new closest L1 superfund cleanup site feature was created.

In [45]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

The next series of cells calculates the L2 distance of each county to the closest Superfund Cleanup site.

In [46]:
sc_site_features_l2 = list(cancer_ml.columns[cancer_ml.columns.str.startswith('SC') & cancer_ml.columns.str.endswith('_l2')])

In [47]:
sc_min_dists_l2 = cancer_ml[sc_site_features_l2].min(axis=1).values
sc_min_dists_l2

array([0.38759385, 0.21098363, 0.83218753, ..., 1.31581102, 1.40861456,
       1.17339805])

A new feature is created in the 'cancer_ml' DataFrame which stores the L2 latitude/longitude distance of each county to the closest Superfund Cleanup site.

In [48]:
cancer_ml['sc_min_dists_l2'] = sc_min_dists_l2

The first row's values of the 'cancer_ml' DataFrame are called to verify that the new closest L2 Superfund Cleanup site feature was created.

In [49]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

In an earlier draft, an experiment was made fitting the individual Superfund Cleanup site distance features to the model. This resulted in extreme overfitting, so the individual features are dropped in the next two cells.

In [50]:
cancer_ml = cancer_ml.drop(columns=sc_site_features_l1)

In [51]:
cancer_ml = cancer_ml.drop(columns=sc_site_features_l2)

In [52]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

## Benchmark 2

This is a good place to output a csv file as a benchmark before more features are added.

In [53]:
cancer_ml.to_csv('cancer_ml_benchmark_2.csv')

In [54]:
cancer_ml = pd.read_csv('cancer_ml_benchmark_2.csv', index_col=['Geography'])

In [55]:
cancer_ml.head(1)

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT  INTPTLONG  State_Alabama  \
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4          0.0       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354       0.0      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041 -82.454058              0   

                                  State_Alaska  State_Arizona  State_Arkansas  State_California  State_Colorado  State_Connecticut  State_Delaware  State_District of Columbia  State_Florida  State_Georgia  State_Hawaii  State_Idaho  State_Illinois  State_Indiana  State_Iowa  State_Kansas  State_Kentucky  State_Louisiana  State_Maine  State_Maryland  State_Massachusetts  State_Michigan  State_Minnesota  State_Mississippi  State_Missouri  State_Montana  State_Nebraska  State_Nevada  State_New Hampshire  State_New Jersey  State_New Mexico  State_New York  State_North Carolina  State_North Dakota  State_Ohio  State_Oklahoma  State_Oregon  State_Pennsylvania  State_Rhode Island  State_South Carolina  State_South Dakota  State_Tennessee  State_Texas  State_Utah  State_Vermont  State_Virginia  State_Washington  State_West Virginia  State_Wisconsin  State_Wyoming   utmda_l1   mskcc_l1    mayo_l1  hopkins_l1     dfb_l1  cleveland_l1  upmcps_l1  hlmcc_l1     mgs_l1  nw_mem_l1     chi_l1  \
Geography                                

# Food Environment Features

Because one's access to quality food can influence one's risk for cancer, a series of features describing the food environment of each county is concatenated into the DataFrame. The source of this data is from research done by the USDA and is called the Food Environment Atlas, available from https://www.ers.usda.gov/data-products/food-environment-atlas/data-access-and-documentation-downloads/#August%202015%20Version . First, the data dictionary for the Food Environment Atlas is loaded as a DataFrame for reference.

In [56]:
fe_data_dict = pd.read_excel('Food_Env_Atlas_August2015_50states_for_merging.xls', sheet_name='Variable List')
fe_data_dict

Category  Category Code                   Sub Category Use?                                      Variable Name            Variable Code Geography              Units
0       Access and Proximity to Grocery Store         ACCESS                            NaN                   Population, low access to store, 2010            LACCESS_POP10    CNTY10              Count
1       Access and Proximity to Grocery Store         ACCESS                            NaN    1          Population, low access to store (%), 2010        PCT_LACCESS_POP10    CNTY10            Percent
2       Access and Proximity to Grocery Store         ACCESS                            NaN                  Low income & low access to store, 2010           LACCESS_LOWI10    CNTY10              Count
3       Access and Proximity to Grocery Store         ACCESS                            NaN    1         Low income & low access to store (%), 2010       PCT_LACCESS_LOWI10    CNTY10            Percent
4       Access and Proximity to Grocery Store         ACCESS                            NaN                     Children, low access to store, 2010          LACCESS_CHILD10    CNTY10              Count
5       Access and Proximity to Grocery Store         ACCESS                            NaN    1            Children, low access to store (%), 2010      PCT_LACCESS_CHILD10    CNTY10            Percent
6       Access and Proximity to Grocery Store         ACCESS                            NaN                      Seniors, low access to store, 2010        LACCESS_SENIORS10    CNTY10              Count
7       Access and Proximity to Grocery Store         ACCESS                            NaN    1             Seniors, low access to store (%), 2010    PCT_LACCESS_SENIORS10    CNTY10            Percent
8       Access and Proximity to Grocery Store         ACCESS                            NaN          Households, no car & low access to store, 2010           LACCESS_HHNV10    CNTY10              Count
9       Access and Proximity to Grocery Store         ACCESS                            NaN    1  Households, no car & low access to store (%), ...       PCT_LACCESS_HHNV10    CNTY10            Percent
10                         Store Availability         STORES                        Grocery    1                               Grocery stores, 2007                   GROC07    CNTY10              Count
11                         Store Availability         STORES                        Grocery    1                               Grocery stores, 2012                   GROC12    CNTY10              Count
12                         Store Availability         STORES                        Grocery    1                 Grocery stores (% change), 2007-12           PCH_GROC_07_12    CNTY10          % change 
13                         Store Availability         STORES                        Grocery    1                     Grocery stores/1,000 pop, 2007                GROCPTH07    CNTY10    # per 1,000 pop
14                         Store Availability         STORES                        Grocery    1                     Grocery stores/1,000 pop, 2012                GROCPTH12    CNTY10    # per 1,000 pop
15                         Store Availability         STORES                        Grocery    1       Grocery stores/1,000 pop (% change), 2007-12        PCH_GROCPTH_07_12    CNTY10          % change 
16                         Store Availability         STORES                   Supercenters    1                   Supercenters & club stores, 2007                 SUPERC07    CNTY10              Count
17                         Store Availability         STORES                   Supercenters    1                   Supercenters & club stores, 2012                 SUPERC12    CNTY10              Count
18                         Store Availability         STORES                   Supercenters    1     Supercenters & club stores (% change), 2007-12         PCH_SUPERC_07_12    CNTY10          % chang

The "Access and Proximity to Grocery Store" variables are first loaded in and then concatenated with the main DataFrame.

In [57]:
access = pd.read_csv('ACCESS_ed.csv', index_col=['Geography'])
access.head()

PCT_LACCESS_POP10  PCT_LACCESS_LOWI10  PCT_LACCESS_CHILD10  PCT_LACCESS_SENIORS10  PCT_LACCESS_HHNV10
Geography                                                                                                                              
Abbeville County, South Carolina          30.016760           14.516552             7.030320               5.157212            6.049947
Acadia Parish, Louisiana                   1.701383            0.572560             0.493074               0.224201            1.797018
Accomack County, Virginia                  4.606049            1.685873             0.718831               1.170231            7.706417
Ada County, Idaho                         18.320609            3.818425             4.945663               1.968186            0.580236
Adair County, Iowa                         7.876416            2.056509             1.811461               1.547285            1.876358

In [58]:
access.shape

(3047, 5)

In [59]:
cancer_ml = pd.concat([cancer_ml, access], axis=1, sort=True)
#pd.concat([cancer_ml, cnty_centroids], axis=1, sort=True)

In [60]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia               221.0             216.2          479.4      38390       32973            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                    True                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     449.310      860.729  37.765944  -75.757807              0   
Ada County, Idaho                 

In [61]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

['PCT_LACCESS_POP10',
 'PCT_LACCESS_LOWI10',
 'PCT_LACCESS_CHILD10',
 'PCT_LACCESS_SENIORS10',
 'PCT_LACCESS_HHNV10']

In [62]:
for col_name in null_value_columns:
    new_col_name = col_name+'_isnull'
    print(col_name)
    cancer_ml[new_col_name] = cancer_ml[col_name].isnull()

PCT_LACCESS_POP10
PCT_LACCESS_LOWI10
PCT_LACCESS_CHILD10
PCT_LACCESS_SENIORS10
PCT_LACCESS_HHNV10


In [63]:
PCT_LACCESS_POP10_med = cancer_ml['PCT_LACCESS_POP10'].median()

In [64]:
cancer_ml['PCT_LACCESS_POP10'] = cancer_ml['PCT_LACCESS_POP10'].fillna(value = PCT_LACCESS_POP10_med)

In [65]:
PCT_LACCESS_LOWI10_med = cancer_ml['PCT_LACCESS_LOWI10'].median()

In [66]:
cancer_ml['PCT_LACCESS_LOWI10'] = cancer_ml['PCT_LACCESS_LOWI10'].fillna(value = PCT_LACCESS_LOWI10_med)

In [67]:
PCT_LACCESS_CHILD10_med = cancer_ml['PCT_LACCESS_CHILD10'].median()

In [68]:
cancer_ml['PCT_LACCESS_CHILD10'] = cancer_ml['PCT_LACCESS_CHILD10'].fillna(value = PCT_LACCESS_CHILD10_med)

In [69]:
PCT_LACCESS_SENIORS10_med = cancer_ml['PCT_LACCESS_SENIORS10'].median()

In [70]:
cancer_ml['PCT_LACCESS_SENIORS10'] = cancer_ml['PCT_LACCESS_SENIORS10'].fillna(value = PCT_LACCESS_SENIORS10_med)

In [71]:
PCT_LACCESS_HHNV10_med = cancer_ml['PCT_LACCESS_HHNV10'].median()

In [72]:
cancer_ml['PCT_LACCESS_HHNV10'] = cancer_ml['PCT_LACCESS_HHNV10'].fillna(value = PCT_LACCESS_HHNV10_med)

In [73]:
cancer_ml.to_csv('cancer_ml_w_access.csv')

In [74]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

[]

In [75]:
cancer_ml.to_csv('cancer_ml_w_access.csv')

## Benchmark 3

In [78]:
cancer_ml = pd.read_csv('cancer_ml_w_access.csv', index_col=['Geography'])

In [79]:
insecurity = pd.read_csv('INSECURITY.csv', index_col=['Geography'])

In [80]:
insecurity.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Abbeville County, South Carolina to Zavala County, Texas
Data columns (total 12 columns):
FOODINSEC_00_02          3046 non-null float64
FOODINSEC_07_09          3046 non-null float64
FOODINSEC_10_12          3046 non-null float64
CH_FOODINSEC_02_12       3046 non-null float64
CH_FOODINSEC_09_12       3046 non-null float64
VLFOODSEC_00_02          3046 non-null float64
VLFOODSEC_07_09          3046 non-null float64
VLFOODSEC_10_12          3046 non-null float64
CH_VLFOODSEC_02_12       3046 non-null float64
CH_VLFOODSEC_09_12       3046 non-null float64
FOODINSEC_CHILD_01_07    3046 non-null float64
FOODINSEC_CHILD_03_11    3046 non-null float64
dtypes: float64(12)
memory usage: 309.5+ KB


In [81]:
insecurity.head()

FOODINSEC_00_02  FOODINSEC_07_09  FOODINSEC_10_12  CH_FOODINSEC_02_12  CH_FOODINSEC_09_12  VLFOODSEC_00_02  VLFOODSEC_07_09  VLFOODSEC_10_12  CH_VLFOODSEC_02_12  CH_VLFOODSEC_09_12  FOODINSEC_CHILD_01_07  FOODINSEC_CHILD_03_11
Geography                                                                                                                                                                                                                                                           
Abbeville County, South Carolina             12.3             13.5             15.4                 3.1                 1.9              4.3              5.0              5.2                 0.9                 0.2                    9.2                    9.8
Acadia Parish, Louisiana                     13.1             10.0             15.7                 2.6                 5.7              2.9              3.3              4.8                 1.9                 1.5                    9.1                    9.0
Accomack County, Virginia                     7.3              9.2              9.2                 1.9                 0.0              1.8              3.6              3.2                 1.4                -0.4                    6.2                    6.2
Ada County, Idaho                            13.7             11.6             14.3                 0.6                 2.7              4.3              4.5              5.3                 1.0                 0.8                    9.7                    8.7
Adair County, Iowa                            9.1             11.5             12.6                 3.5                 1.1              2.8              5.0              4.8                 2.0                -0.2                    7.5                    8.3

In [82]:
cancer_ml = pd.concat([cancer_ml, insecurity], axis=1, sort=True)

In [83]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia               221.0             216.2          479.4      38390       32973            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                    True                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     449.310      860.729  37.765944  -75.757807              0   
Ada County, Idaho                 

In [84]:
insecurity.columns

Index(['FOODINSEC_00_02', 'FOODINSEC_07_09', 'FOODINSEC_10_12', 'CH_FOODINSEC_02_12', 'CH_FOODINSEC_09_12', 'VLFOODSEC_00_02', 'VLFOODSEC_07_09', 'VLFOODSEC_10_12', 'CH_VLFOODSEC_02_12', 'CH_VLFOODSEC_09_12', 'FOODINSEC_CHILD_01_07', 'FOODINSEC_CHILD_03_11'], dtype='object')

In [85]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

['FOODINSEC_00_02',
 'FOODINSEC_07_09',
 'FOODINSEC_10_12',
 'CH_FOODINSEC_02_12',
 'CH_FOODINSEC_09_12',
 'VLFOODSEC_00_02',
 'VLFOODSEC_07_09',
 'VLFOODSEC_10_12',
 'CH_VLFOODSEC_02_12',
 'CH_VLFOODSEC_09_12',
 'FOODINSEC_CHILD_01_07',
 'FOODINSEC_CHILD_03_11']

In [86]:
for col_name in null_value_columns:
    new_col_name = col_name+'_isnull'
    print(col_name)
    cancer_ml[new_col_name] = cancer_ml[col_name].isnull()

FOODINSEC_00_02
FOODINSEC_07_09
FOODINSEC_10_12
CH_FOODINSEC_02_12
CH_FOODINSEC_09_12
VLFOODSEC_00_02
VLFOODSEC_07_09
VLFOODSEC_10_12
CH_VLFOODSEC_02_12
CH_VLFOODSEC_09_12
FOODINSEC_CHILD_01_07
FOODINSEC_CHILD_03_11


In [87]:
FOODINSEC_00_02_med = cancer_ml['FOODINSEC_00_02'].median()

In [88]:
cancer_ml['FOODINSEC_00_02'] = cancer_ml['FOODINSEC_00_02'].fillna(value = FOODINSEC_00_02_med)

In [89]:
FOODINSEC_07_09_med = cancer_ml['FOODINSEC_07_09'].median()

In [90]:
cancer_ml['FOODINSEC_07_09'] = cancer_ml['FOODINSEC_07_09'].fillna(value = FOODINSEC_07_09_med)

In [91]:
FOODINSEC_10_12_med = cancer_ml['FOODINSEC_10_12'].median()

In [92]:
cancer_ml['FOODINSEC_10_12'] = cancer_ml['FOODINSEC_10_12'].fillna(value = FOODINSEC_10_12_med)

In [93]:
CH_FOODINSEC_02_12_med = cancer_ml['CH_FOODINSEC_02_12'].median()

In [94]:
cancer_ml['CH_FOODINSEC_02_12'] = cancer_ml['CH_FOODINSEC_02_12'].fillna(value = CH_FOODINSEC_02_12_med)

In [95]:
CH_FOODINSEC_09_12_med = cancer_ml['CH_FOODINSEC_09_12'].median()

In [96]:
cancer_ml['CH_FOODINSEC_09_12'] = cancer_ml['CH_FOODINSEC_09_12'].fillna(value = CH_FOODINSEC_09_12_med)

In [97]:
VLFOODSEC_00_02_med = cancer_ml['VLFOODSEC_00_02'].median()

In [98]:
cancer_ml['VLFOODSEC_00_02'] = cancer_ml['VLFOODSEC_00_02'].fillna(value = VLFOODSEC_00_02_med)

In [99]:
VLFOODSEC_07_09_med = cancer_ml['VLFOODSEC_07_09'].median()

In [100]:
cancer_ml['VLFOODSEC_07_09'] = cancer_ml['VLFOODSEC_07_09'].fillna(value = VLFOODSEC_07_09_med)

In [101]:
VLFOODSEC_10_12_med = cancer_ml['VLFOODSEC_10_12'].median()

In [102]:
cancer_ml['VLFOODSEC_10_12'] = cancer_ml['VLFOODSEC_10_12'].fillna(value = VLFOODSEC_10_12_med)

In [103]:
CH_VLFOODSEC_02_12_med = cancer_ml['CH_VLFOODSEC_02_12'].median()

In [104]:
cancer_ml['CH_VLFOODSEC_02_12'] = cancer_ml['CH_VLFOODSEC_02_12'].fillna(value = CH_VLFOODSEC_02_12_med)

In [105]:
CH_VLFOODSEC_09_12_med = cancer_ml['CH_VLFOODSEC_09_12'].median()

In [106]:
cancer_ml['CH_VLFOODSEC_09_12'] = cancer_ml['CH_VLFOODSEC_09_12'].fillna(value = CH_VLFOODSEC_09_12_med)

In [107]:
FOODINSEC_CHILD_01_07_med = cancer_ml['FOODINSEC_CHILD_01_07'].median()

In [108]:
cancer_ml['FOODINSEC_CHILD_01_07'] = cancer_ml['FOODINSEC_CHILD_01_07'].fillna(value = FOODINSEC_CHILD_01_07_med)

In [109]:
FOODINSEC_CHILD_03_11_med = cancer_ml['FOODINSEC_CHILD_03_11'].median()

In [110]:
cancer_ml['FOODINSEC_CHILD_03_11'] = cancer_ml['FOODINSEC_CHILD_03_11'].fillna(value = FOODINSEC_CHILD_03_11_med)

In [111]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

[]

## Checkpoint 4

In [112]:
cancer_ml.to_csv('cancer_ml_w_access_insecurity.csv')

In [113]:
cancer_ml = pd.read_csv('cancer_ml_w_access_insecurity.csv', index_col=['Geography'])

In [114]:
local = pd.read_csv('LOCAL.csv', index_col=['Geography'])

In [115]:
local.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Abbeville County, South Carolina to Zavala County, Texas
Data columns (total 37 columns):
PCT_LOCLFARM07          2955 non-null float64
PCT_LOCLSALE07          2711 non-null float64
PC_DIRSALES07           2801 non-null float64
FMRKT09                 3045 non-null float64
FMRKT13                 3046 non-null float64
PCH_FMRKT_09_13         2577 non-null float64
FMRKTPTH09              3045 non-null float64
FMRKTPTH13              3046 non-null float64
PCH_FMRKTPTH_09_13      2577 non-null float64
PCT_FMRKT_SNAP13        2149 non-null float64
PCT_FMRKT_WIC13         2149 non-null float64
PCT_FMRKT_WICCASH13     2149 non-null float64
PCT_FMRKT_SFMNP13       2149 non-null float64
PCT_FRMKT_FRVEG13       2149 non-null float64
PCT_FRMKT_ANMLPROD13    2149 non-null float64
PCT_FMRKT_OTHER13       2149 non-null float64
VEG_FARMS07             3001 non-null float64
VEG_ACRES07             2463 non-null float64
VEG_ACRESPTH07         

In [116]:
local.head()

PCT_LOCLFARM07  PCT_LOCLSALE07  PC_DIRSALES07  FMRKT09  FMRKT13  PCH_FMRKT_09_13  FMRKTPTH09  FMRKTPTH13  PCH_FMRKTPTH_09_13  PCT_FMRKT_SNAP13  PCT_FMRKT_WIC13  PCT_FMRKT_WICCASH13  PCT_FMRKT_SFMNP13  PCT_FRMKT_FRVEG13  PCT_FRMKT_ANMLPROD13  PCT_FMRKT_OTHER13  VEG_FARMS07  VEG_ACRES07  VEG_ACRESPTH07  FRESHVEG_FARMS07  FRESHVEG_ACRES07  FRESHVEG_ACRESPTH07  ORCHARD_FARMS07  ORCHARD_ACRES07  ORCHARD_ACRESPTH07  BERRY_FARMS07  BERRY_ACRES07  BERRY_ACRESPTH07  SLHOUSE07  GHVEG_FARMS07  GHVEG_SQFT07  GHVEG_SQFTPTH07  FOODHUB12  CSA07  AGRITRSM_OPS07  AGRITRSM_RCT07  FARM_TO_SCHOOL
Geography                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Abbeville County, South Carolina             6.9             0.9           3.73      2.0      2.0         0.000000    0.079688    0.079678           -0.011952               0.0              0.0                  0.0               50.0               50.0                  50.0               50.0         23.0         61.0            2.40              23.0              61.0             2.409353             21.0             79.0            3.120310            8.0           11.0          0.434473        0.0            0.0           0.0              0.0        0.0    1.0             4.0         27000.0             0.0
Acadia Parish, Louisiana                     2.0             0.7           7.68      0.0      0.0         0.000000    0.000000    0.000000            0.000000               NaN              NaN                  NaN                NaN                NaN                   NaN                NaN          2.0          NaN             NaN               1.0               NaN                  NaN              9.0             59.0            0.988026            2.0            NaN               NaN        1.0            0.0           0.0              0.0        0.0    1.0             2.0             NaN             0.0
Accomack County, Virginia                    6.5             0.0           1.72      1.0      2.0       100.000000    0.026000    0.059986          130.718935              50.0              0.0                  0.0                0.0              100.0                 100.0              100.0         35.0       6270.0          163.39              30.0            3715.0            96.606423              8.0             49.0            1.274217            3.0            NaN               NaN        1.0            0.0           0.0              0.0        0.0    1.0             1.0             NaN             0.0
Ada County, Idaho                           16.6             0.6           2.29      9.0     10.0        11.111111    0.023398    0.024446            4.482108              40.0              0.0                  0.0                0.0               80.0                  80.0               80.0         39.0        992.0            2.66              35.0               NaN                  NaN             47.0            137.0            0.367818            7.0            1.0          0.002685        4.0            3.0           NaN              NaN        1.0   15.0             6.0             NaN             0.0
Adair County, Iowa                           2.5             0.0           6.95      2.0      2.0         0.000000    0.272109    0.267344           -1.751103               0.0              0.0                  0.0                0.0                0.0                   0.0                0.0          3.0          6.0       

In [117]:
cancer_ml = pd.concat([cancer_ml, local], axis=1, sort=True)
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia               221.0             216.2          479.4      38390       32973            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                    True                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     449.310      860.729  37.765944  -75.757807              0   
Ada County, Idaho                 

In [118]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

['PCT_LOCLFARM07',
 'PCT_LOCLSALE07',
 'PC_DIRSALES07',
 'FMRKT09',
 'FMRKT13',
 'PCH_FMRKT_09_13',
 'FMRKTPTH09',
 'FMRKTPTH13',
 'PCH_FMRKTPTH_09_13',
 'PCT_FMRKT_SNAP13',
 'PCT_FMRKT_WIC13',
 'PCT_FMRKT_WICCASH13',
 'PCT_FMRKT_SFMNP13',
 'PCT_FRMKT_FRVEG13',
 'PCT_FRMKT_ANMLPROD13',
 'PCT_FMRKT_OTHER13',
 'VEG_FARMS07',
 'VEG_ACRES07',
 'VEG_ACRESPTH07',
 'FRESHVEG_FARMS07',
 'FRESHVEG_ACRES07',
 'FRESHVEG_ACRESPTH07',
 'ORCHARD_FARMS07',
 'ORCHARD_ACRES07',
 'ORCHARD_ACRESPTH07',
 'BERRY_FARMS07',
 'BERRY_ACRES07',
 'BERRY_ACRESPTH07',
 'SLHOUSE07',
 'GHVEG_FARMS07',
 'GHVEG_SQFT07',
 'GHVEG_SQFTPTH07',
 'FOODHUB12',
 'CSA07',
 'AGRITRSM_OPS07',
 'AGRITRSM_RCT07',
 'FARM_TO_SCHOOL']

In [119]:
for col_name in null_value_columns:
    new_col_name = col_name+'_isnull'
    print(col_name)
    cancer_ml[new_col_name] = cancer_ml[col_name].isnull()

PCT_LOCLFARM07
PCT_LOCLSALE07
PC_DIRSALES07
FMRKT09
FMRKT13
PCH_FMRKT_09_13
FMRKTPTH09
FMRKTPTH13
PCH_FMRKTPTH_09_13
PCT_FMRKT_SNAP13
PCT_FMRKT_WIC13
PCT_FMRKT_WICCASH13
PCT_FMRKT_SFMNP13
PCT_FRMKT_FRVEG13
PCT_FRMKT_ANMLPROD13
PCT_FMRKT_OTHER13
VEG_FARMS07
VEG_ACRES07
VEG_ACRESPTH07
FRESHVEG_FARMS07
FRESHVEG_ACRES07
FRESHVEG_ACRESPTH07
ORCHARD_FARMS07
ORCHARD_ACRES07
ORCHARD_ACRESPTH07
BERRY_FARMS07
BERRY_ACRES07
BERRY_ACRESPTH07
SLHOUSE07
GHVEG_FARMS07
GHVEG_SQFT07
GHVEG_SQFTPTH07
FOODHUB12
CSA07
AGRITRSM_OPS07
AGRITRSM_RCT07
FARM_TO_SCHOOL


In [120]:
PCT_LOCLFARM07_med = cancer_ml['PCT_LOCLFARM07'].median()

In [121]:
cancer_ml['PCT_LOCLFARM07'] = cancer_ml['PCT_LOCLFARM07'].fillna(value = PCT_LOCLFARM07_med)

In [122]:
PCT_LOCLSALE07_med = cancer_ml['PCT_LOCLSALE07'].median()

In [123]:
cancer_ml['PCT_LOCLSALE07'] = cancer_ml['PCT_LOCLSALE07'].fillna(value = PCT_LOCLSALE07_med)

In [124]:
PC_DIRSALES07_med = cancer_ml['PC_DIRSALES07'].median()

In [125]:
cancer_ml['PC_DIRSALES07'] = cancer_ml['PC_DIRSALES07'].fillna(value = PC_DIRSALES07_med)

In [126]:
FMRKT09_med = cancer_ml['FMRKT09'].median()

In [127]:
cancer_ml['FMRKT09'] = cancer_ml['FMRKT09'].fillna(value = FMRKT09_med)

In [128]:
FMRKT13_med = cancer_ml['FMRKT13'].median()

In [129]:
cancer_ml['FMRKT13'] = cancer_ml['FMRKT13'].fillna(value = FMRKT13_med)

In [130]:
PCH_FMRKT_09_13_med = cancer_ml['PCH_FMRKT_09_13'].median()

In [131]:
cancer_ml['PCH_FMRKT_09_13'] = cancer_ml['PCH_FMRKT_09_13'].fillna(value = PCH_FMRKT_09_13_med)

In [132]:
FMRKTPTH09_med = cancer_ml['FMRKTPTH09'].median()

In [133]:
cancer_ml['FMRKTPTH09'] = cancer_ml['FMRKTPTH09'].fillna(value = FMRKTPTH09_med)

In [134]:
FMRKTPTH13_med = cancer_ml['FMRKTPTH13'].median()

In [135]:
cancer_ml['FMRKTPTH13'] = cancer_ml['FMRKTPTH13'].fillna(value = FMRKTPTH13_med)

In [136]:
PCH_FMRKTPTH_09_13_med = cancer_ml['PCH_FMRKTPTH_09_13'].median()

In [137]:
cancer_ml['PCH_FMRKTPTH_09_13'] = cancer_ml['PCH_FMRKTPTH_09_13'].fillna(value = PCH_FMRKTPTH_09_13_med)

In [138]:
PCT_FMRKT_SNAP13_med = cancer_ml['PCT_FMRKT_SNAP13'].median()

In [139]:
cancer_ml['PCT_FMRKT_SNAP13'] = cancer_ml['PCT_FMRKT_SNAP13'].fillna(value = PCT_FMRKT_SNAP13_med)

In [140]:
PCT_FMRKT_WIC13_med = cancer_ml['PCT_FMRKT_WIC13'].median()

In [141]:
cancer_ml['PCT_FMRKT_WIC13'] = cancer_ml['PCT_FMRKT_WIC13'].fillna(value = PCT_FMRKT_WIC13_med)

In [142]:
PCT_FMRKT_WICCASH13_med = cancer_ml['PCT_FMRKT_WICCASH13'].median()

In [143]:
cancer_ml['PCT_FMRKT_WICCASH13'] = cancer_ml['PCT_FMRKT_WICCASH13'].fillna(value = PCT_FMRKT_WICCASH13_med)

In [144]:
PCT_FMRKT_SFMNP13_med = cancer_ml['PCT_FMRKT_SFMNP13'].median()

In [145]:
cancer_ml['PCT_FMRKT_SFMNP13'] = cancer_ml['PCT_FMRKT_SFMNP13'].fillna(value = PCT_FMRKT_SFMNP13_med)

In [146]:
PCT_FRMKT_FRVEG13_med = cancer_ml['PCT_FRMKT_FRVEG13'].median()

In [147]:
cancer_ml['PCT_FRMKT_FRVEG13'] = cancer_ml['PCT_FRMKT_FRVEG13'].fillna(value = PCT_FRMKT_FRVEG13_med)

In [148]:
PCT_FRMKT_ANMLPROD13_med = cancer_ml['PCT_FRMKT_ANMLPROD13'].median()

In [149]:
cancer_ml['PCT_FRMKT_ANMLPROD13'] = cancer_ml['PCT_FRMKT_ANMLPROD13'].fillna(value = PCT_FRMKT_ANMLPROD13_med)

In [150]:
PCT_FMRKT_OTHER13_med = cancer_ml['PCT_FMRKT_OTHER13'].median()

In [151]:
cancer_ml['PCT_FMRKT_OTHER13'] = cancer_ml['PCT_FMRKT_OTHER13'].fillna(value = PCT_FMRKT_OTHER13_med)

In [152]:
VEG_FARMS07_med = cancer_ml['VEG_FARMS07'].median()

In [153]:
cancer_ml['VEG_FARMS07'] = cancer_ml['VEG_FARMS07'].fillna(value = VEG_FARMS07_med)

In [154]:
VEG_ACRES07_med = cancer_ml['VEG_ACRES07'].median()

In [155]:
cancer_ml['VEG_ACRES07'] = cancer_ml['VEG_ACRES07'].fillna(value = VEG_ACRES07_med)

In [156]:
VEG_ACRESPTH07_med = cancer_ml['VEG_ACRESPTH07'].median()

In [157]:
cancer_ml['VEG_ACRESPTH07'] = cancer_ml['VEG_ACRESPTH07'].fillna(value = VEG_ACRESPTH07_med)

In [158]:
FRESHVEG_FARMS07_med = cancer_ml['FRESHVEG_FARMS07'].median()

In [159]:
cancer_ml['FRESHVEG_FARMS07'] = cancer_ml['FRESHVEG_FARMS07'].fillna(value = FRESHVEG_FARMS07_med)

In [160]:
FRESHVEG_ACRES07_med = cancer_ml['FRESHVEG_ACRES07'].median()

In [161]:
cancer_ml['FRESHVEG_ACRES07'] = cancer_ml['FRESHVEG_ACRES07'].fillna(value = FRESHVEG_ACRES07_med)

In [162]:
FRESHVEG_ACRESPTH07_med = cancer_ml['FRESHVEG_ACRESPTH07'].median()

In [163]:
cancer_ml['FRESHVEG_ACRESPTH07'] = cancer_ml['FRESHVEG_ACRESPTH07'].fillna(value = FRESHVEG_ACRESPTH07_med)

In [164]:
ORCHARD_FARMS07_med = cancer_ml['ORCHARD_FARMS07'].median()

In [165]:
cancer_ml['ORCHARD_FARMS07'] = cancer_ml['ORCHARD_FARMS07'].fillna(value = ORCHARD_FARMS07_med)

In [166]:
ORCHARD_ACRES07_med = cancer_ml['ORCHARD_ACRES07'].median()

In [167]:
cancer_ml['ORCHARD_ACRES07'] = cancer_ml['ORCHARD_ACRES07'].fillna(value = ORCHARD_ACRES07_med)

In [168]:
ORCHARD_ACRESPTH07_med = cancer_ml['ORCHARD_ACRESPTH07'].median()

In [169]:
cancer_ml['ORCHARD_ACRESPTH07'] = cancer_ml['ORCHARD_ACRESPTH07'].fillna(value = ORCHARD_ACRESPTH07_med)

In [170]:
BERRY_FARMS07_med = cancer_ml['BERRY_FARMS07'].median()

In [171]:
cancer_ml['BERRY_FARMS07'] = cancer_ml['BERRY_FARMS07'].fillna(value = BERRY_FARMS07_med)

In [172]:
BERRY_ACRES07_med = cancer_ml['BERRY_ACRES07'].median()

In [173]:
cancer_ml['BERRY_ACRES07'] = cancer_ml['BERRY_ACRES07'].fillna(value = BERRY_ACRES07_med)

In [174]:
BERRY_ACRESPTH07_med = cancer_ml['BERRY_ACRESPTH07'].median()

In [175]:
cancer_ml['BERRY_ACRESPTH07'] = cancer_ml['BERRY_ACRESPTH07'].fillna(value = BERRY_ACRESPTH07_med)

In [176]:
SLHOUSE07_med = cancer_ml['SLHOUSE07'].median()

In [177]:
cancer_ml['SLHOUSE07'] = cancer_ml['SLHOUSE07'].fillna(value = SLHOUSE07_med)

In [178]:
GHVEG_FARMS07_med = cancer_ml['GHVEG_FARMS07'].median()

In [179]:
cancer_ml['GHVEG_FARMS07'] = cancer_ml['GHVEG_FARMS07'].fillna(value = GHVEG_FARMS07_med)

In [180]:
GHVEG_SQFT07_med = cancer_ml['GHVEG_SQFT07'].median()

In [181]:
cancer_ml['GHVEG_SQFT07'] = cancer_ml['GHVEG_SQFT07'].fillna(value = GHVEG_SQFT07_med)

In [182]:
GHVEG_SQFTPTH07_med = cancer_ml['GHVEG_SQFTPTH07'].median()

In [183]:
cancer_ml['GHVEG_SQFTPTH07'] = cancer_ml['GHVEG_SQFTPTH07'].fillna(value = GHVEG_SQFTPTH07_med)

In [184]:
FOODHUB12_med = cancer_ml['FOODHUB12'].median()

In [185]:
cancer_ml['FOODHUB12'] = cancer_ml['FOODHUB12'].fillna(value = FOODHUB12_med)

In [186]:
CSA07_med = cancer_ml['CSA07'].median()

In [187]:
cancer_ml['CSA07'] = cancer_ml['CSA07'].fillna(value = CSA07_med)

In [188]:
AGRITRSM_OPS07_med = cancer_ml['AGRITRSM_OPS07'].median()

In [189]:
cancer_ml['AGRITRSM_OPS07'] = cancer_ml['AGRITRSM_OPS07'].fillna(value = AGRITRSM_OPS07_med)

In [190]:
AGRITRSM_RCT07_med = cancer_ml['AGRITRSM_RCT07'].median()

In [191]:
cancer_ml['AGRITRSM_RCT07'] = cancer_ml['AGRITRSM_RCT07'].fillna(value = AGRITRSM_RCT07_med)

In [192]:
FARM_TO_SCHOOL_med = cancer_ml['FARM_TO_SCHOOL'].median()

In [193]:
cancer_ml['FARM_TO_SCHOOL'] = cancer_ml['FARM_TO_SCHOOL'].fillna(value = FARM_TO_SCHOOL_med)

In [194]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

[]

## Checkpoint 5

In [195]:
cancer_ml.to_csv('cancer_ml_w_acc_insec_local.csv')

In [196]:
cancer_ml = pd.read_csv('cancer_ml_w_acc_insec_local.csv', index_col=['Geography'])

In [197]:
health = pd.read_csv('HEALTH.csv', index_col=['Geography'])

In [198]:
health.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Abbeville County, South Carolina to Zavala County, Texas
Data columns (total 16 columns):
PCT_DIABETES_ADULTS09    3047 non-null float64
PCT_DIABETES_ADULTS10    3047 non-null float64
PCT_OBESE_ADULTS09       3047 non-null float64
PCT_OBESE_ADULTS10       3047 non-null float64
PCT_OBESE_ADULTS13       3047 non-null float64
PCT_OBESE_CHILD08        2655 non-null float64
PCT_OBESE_CHILD11        2675 non-null float64
PCH_OBESE_CHILD_08_11    2601 non-null float64
PCT_HSPA09               2436 non-null float64
RECFAC07                 3047 non-null int64
RECFAC12                 3047 non-null int64
PCH_RECFAC_07_12         2927 non-null float64
RECFACPTH07              3047 non-null float64
RECFACPTH12              3047 non-null float64
PCH_RECFACPTH_07_12      2927 non-null float64
NATAMEN                  3024 non-null float64
dtypes: float64(14), int64(2)
memory usage: 404.7+ KB


In [199]:
health.head()

PCT_DIABETES_ADULTS09  PCT_DIABETES_ADULTS10  PCT_OBESE_ADULTS09  PCT_OBESE_ADULTS10  PCT_OBESE_ADULTS13  PCT_OBESE_CHILD08  PCT_OBESE_CHILD11  PCH_OBESE_CHILD_08_11  PCT_HSPA09  RECFAC07  RECFAC12  PCH_RECFAC_07_12  RECFACPTH07  RECFACPTH12  PCH_RECFACPTH_07_12  NATAMEN
Geography                                                                                                                                                                                                                                                                                                        
Abbeville County, South Carolina                   13.2                   13.6                32.6                34.8                31.7               10.4                NaN                    NaN        17.1         0         0          0.000000     0.000000     0.000000             0.000000      3.0
Acadia Parish, Louisiana                            9.6                    9.9                32.7                32.2                33.1               16.6               14.5                   -2.1        23.0         6         5        -16.666667     0.100477     0.080760           -19.623821      3.0
Accomack County, Virginia                          12.4                   12.9                33.4                35.5                27.2               23.7               18.6                   -5.1         NaN         6         1        -83.333333     0.156027     0.029993           -80.776921      4.0
Ada County, Idaho                                   6.8                    7.3                23.3                23.5                29.6               10.1                9.8                   -0.3        27.6        36        43         19.444444     0.096653     0.105119             8.759119      4.0
Adair County, Iowa                                 10.5                   11.0                30.6                31.8                31.3               17.3               14.0                   -3.3         NaN         0         1               NaN     0.000000     0.133672                  NaN      3.0

In [200]:
cancer_ml = pd.concat([cancer_ml, health], axis=1, sort=True)
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia               221.0             216.2          479.4      38390       32973            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                    True                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     449.310      860.729  37.765944  -75.757807              0   
Ada County, Idaho                 

In [201]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

['PCT_OBESE_CHILD08',
 'PCT_OBESE_CHILD11',
 'PCH_OBESE_CHILD_08_11',
 'PCT_HSPA09',
 'PCH_RECFAC_07_12',
 'PCH_RECFACPTH_07_12',
 'NATAMEN']

In [202]:
for col_name in null_value_columns:
    new_col_name = col_name+'_isnull'
    print(col_name)
    cancer_ml[new_col_name] = cancer_ml[col_name].isnull()

PCT_OBESE_CHILD08
PCT_OBESE_CHILD11
PCH_OBESE_CHILD_08_11
PCT_HSPA09
PCH_RECFAC_07_12
PCH_RECFACPTH_07_12
NATAMEN


In [203]:
PCT_OBESE_CHILD08_med = cancer_ml['PCT_OBESE_CHILD08'].median()

In [204]:
cancer_ml['PCT_OBESE_CHILD08'] = cancer_ml['PCT_OBESE_CHILD08'].fillna(value = PCT_OBESE_CHILD08_med)

In [205]:
PCT_OBESE_CHILD11_med = cancer_ml['PCT_OBESE_CHILD11'].median()

In [206]:
cancer_ml['PCT_OBESE_CHILD11'] = cancer_ml['PCT_OBESE_CHILD11'].fillna(value = PCT_OBESE_CHILD11_med)

In [207]:
PCH_OBESE_CHILD_08_11_med = cancer_ml['PCH_OBESE_CHILD_08_11'].median()

In [208]:
cancer_ml['PCH_OBESE_CHILD_08_11'] = cancer_ml['PCH_OBESE_CHILD_08_11'].fillna(value = PCH_OBESE_CHILD_08_11_med)

In [209]:
PCT_HSPA09_med = cancer_ml['PCT_HSPA09'].median()

In [210]:
cancer_ml['PCT_HSPA09'] = cancer_ml['PCT_HSPA09'].fillna(value = PCT_HSPA09_med)

In [211]:
PCH_RECFAC_07_12_med = cancer_ml['PCH_RECFAC_07_12'].median()

In [212]:
cancer_ml['PCH_RECFAC_07_12'] = cancer_ml['PCH_RECFAC_07_12'].fillna(value = PCH_RECFAC_07_12_med)

In [213]:
PCH_RECFACPTH_07_12_med = cancer_ml['PCH_RECFACPTH_07_12'].median()

In [214]:
cancer_ml['PCH_RECFACPTH_07_12'] = cancer_ml['PCH_RECFACPTH_07_12'].fillna(value = PCH_RECFACPTH_07_12_med)

In [215]:
NATAMEN_med = cancer_ml['NATAMEN'].median()

In [216]:
cancer_ml['NATAMEN'] = cancer_ml['NATAMEN'].fillna(value = NATAMEN_med)

In [217]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

[]

In [218]:
cancer_ml.to_csv('cancer_ml_w_acc_insec_local_health.csv')

## Checkpoint 6

In [219]:
cancer_ml = pd.read_csv('cancer_ml_w_acc_insec_local_health.csv', index_col = ['Geography'])

In [220]:
soc_econ = pd.read_csv('SOCIOECONOMIC.csv', index_col = ['Geography'])

In [221]:
soc_econ.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3047 entries, Abbeville County, South Carolina to Zavala County, Texas
Data columns (total 5 columns):
PERPOV10          3047 non-null int64
CHILDPOVRATE10    3047 non-null float64
PERCHLDPOV10      3047 non-null int64
METRO13           3047 non-null int64
POPLOSS00         3047 non-null object
dtypes: float64(1), int64(3), object(1)
memory usage: 142.8+ KB


In [222]:
soc_econ.head()

PERPOV10  CHILDPOVRATE10  PERCHLDPOV10  METRO13 POPLOSS00
Geography                                                                                  
Abbeville County, South Carolina         0            26.6             0        0         0
Acadia Parish, Louisiana                 1            29.6             1        1         0
Accomack County, Virginia                0            28.7             1        0         0
Ada County, Idaho                        0            16.1             0        1         0
Adair County, Iowa                       0            14.1             0        0         1

In [223]:
cancer_ml = pd.concat([cancer_ml, soc_econ], axis=1, sort=True)

In [224]:
cancer_ml.head()

avgAnnCount  TARGET_deathRate  incidenceRate  medIncome  popEst2015  povertyPercent  studyPerCap  MedianAge  MedianAgeMale  MedianAgeFemale  AvgHouseholdSize  PercentMarried  PctNoHS18_24  PctHS18_24  PctSomeCol18_24  PctBachDeg18_24  PctHS25_Over  PctBachDeg25_Over  PctEmployed16_Over  PctUnemployed16_Over  PctPrivateCoverage  PctPrivateCoverageAlone  PctEmpPrivCoverage  PctPublicCoverage  PctPublicCoverageAlone   PctWhite   PctBlack  PctAsian  PctOtherRace  PctMarriedHouseholds  BirthRate  PctSomeCol18_24_isnull  PctEmployed16_Over_isnull  PctPrivateCoverageAlone_isnull  age_gt_100  household_lt_1  binnedInc_(34218.1, 37413.8]  binnedInc_(37413.8, 40362.7]  binnedInc_(40362.7, 42724.4]  binnedInc_(42724.4, 45201]  binnedInc_(45201, 48021.6]  binnedInc_(48021.6, 51046.4]  binnedInc_(51046.4, 54545.6]  binnedInc_(54545.6, 61494.5]  binnedInc_(61494.5, 125635]  binnedInc_[22640, 34218.1]  ALAND_SQMI  AWATER_SQMI   INTPTLAT   INTPTLONG  State_Alabama  \
Abbeville County, South Carolina        143.0             183.7          430.9      35525       24932            21.4     0.000000       43.3           40.7             44.9              2.52            46.8          11.2        40.0             40.4              3.2          37.5                8.6                45.9                  10.7                56.6                     41.8                37.6               43.8                    25.9  69.888387  27.947354  0.000000      0.240029             47.299697   5.823784                    True                      False                           False       False           False                             1                             0                             0                           0                           0                             0                             0                             0                            0                           0     491.427       20.554  34.229041  -82.454058              0   
Acadia Parish, Louisiana                323.0             230.5          492.7      40269       62577            22.0     0.000000       35.7           34.7             37.2              2.70            47.3          24.6        35.9             36.6              2.9          39.2                7.6                52.0                  10.1                56.5                     44.6                38.9               37.4                    23.1  78.973023  17.434808  0.194650      1.000595             47.095004   6.938636                   False                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     655.169        2.285  30.291497  -92.411037              0   
Accomack County, Virginia               221.0             216.2          479.4      38390       32973            19.4     0.000000       45.3           42.7             47.3              2.29            52.6          26.6        40.4             40.4             12.9          39.9               11.0                53.1                   6.8                61.8                     43.9                37.3               36.7                    18.4  68.008455  28.675827  0.144949      1.322663             47.467946   4.349749                    True                      False                           False       False           False                             0                             1                             0                           0                           0                             0                             0                             0                            0                           0     449.310      860.729  37.765944  -75.757807              0   
Ada County, Idaho                 

In [225]:
null_value_columns = list(cancer_ml.columns[(cancer_ml.isnull().sum()>0) | (cancer_ml.isna().sum()>0)])
null_value_columns

[]

In [226]:
cancer_ml.to_csv('cancer_ml2.csv')